### ISSUE TITLE
Error: Cannot get name of node

### ISSUE THREAD

**Issue by cain** [psteinroe/supabase-to-zod#29]
Anyone else had this same issue?

command: `pnpm supabase-to-zod --input ./src/lib/types/database.types.ts --output schemas.ts` 

```
Error: Cannot get name of node
    at getNodeName (file:///Users/cain/Code/pub-sveltekit/node_modules/.pnpm/supabase-to-zod@1.0.5/node_modules/supabase-to-zod/dist/chunk-DCTSIM2S.js:15:11)
    at file:///Users/cain/Code/pub-sveltekit/node_modules/.pnpm/supabase-to-zod@1.0.5/node_modules/supabase-to-zod/dist/chunk-DCTSIM2S.js:88:44
    at visitNodes (/Users/cain/Code/pub-sveltekit/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:28081:24)
    at forEachChildInTypeLiteral (/Users/cain/Code/pub-sveltekit/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:28600:18)
    at forEachChild (/Users/cain/Code/pub-sveltekit/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:28166:37)
    at NodeObject.forEachChild (/Users/cain/Code/pub-sveltekit/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:144062:18)
    at file:///Users/cain/Code/pub-sveltekit/node_modules/.pnpm/supabase-to-zod@1.0.5/node_modules/supabase-to-zod/dist/chunk-DCTSIM2S.js:87:28
    at visitNode2 (/Users/cain/Code/pub-sveltekit/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:28073:20)
    at forEachChildInPropertySignature (/Users/cain/Code/pub-sveltekit/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:28541:140)
    at forEachChild (/Users/cain/Code/pub-sveltekit/node_modules/.pnpm/typescript@5.3.3/node_modules/typescript/lib/typescript.js:28166:37)

```

<img width="900" alt="CleanShot 2024-04-03 at 19 48 25@2x" src="https://github.com/psteinroe/supabase-to-zod/assets/15246256/d8926723-0df2-4010-804f-ce105b4022da">

**Comment by TomasHubelbauer** [comment]
@cain FYI this might be fixed in 1.0.6
